Move setup.py configs to pyproject.toml

diff --git a/.github/workflows/main-build-and-publish.yml b/.github/workflows/main-build-and-publish.yml
--- a/.github/workflows/main-build-and-publish.yml
+++ b/.github/workflows/main-build-and-publish.yml
@@ -31,8 +31,7 @@ jobs:
           pip install .[all]
           pip uninstall -y pytest-helm-templates
           pip freeze > requirements.txt
-          git diff --quiet
-          if [ ! $? -eq 0 ]; then
+          if ! `git diff --quiet`; then
             echo "pip freeze caused file changes, failing!"
             exit 1
           fi
@@ -41,6 +40,10 @@ jobs:
         run: |
           source venv/bin/activate
           make style
+          if ! `git diff --quiet`; then
+            echo "make style caused file changes, failing!"
+            exit 1
+          fi
 
       - name: Run tests and build package
         run: |
@@ -48,6 +51,7 @@ jobs:
           coverage run -m pytest
           coverage report | tee .meta/coverage/report.txt
           coverage-badge -f -o .meta/coverage/badge.svg
+          export SETUPTOOLS_SCM_PRETEND_VERSION_FOR_PYTEST_HELM_TEMPLATES="$(cat VERSION)"
           python -m build
 
       - name: Checkout tdg5/github-action-pack
